
name: build
on:
  push:
    branches:
      - 'master'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          language: ["go"]
          include:
            - goarch: amd64
              goos: linux
            - goarch: amd64
              goos: darwin
            - goarch: arm64
              goos: linux
            - goarch: arm64
              goos: darwin

    steps:
      - uses: actions/checkout@v3 

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
  
      - name: Build
        run: go build -v ./...
  
      - name: Packaging
        run: |
          pwd
          ls -l
          tar czf /wechatrobot/wechatrobot-${{ matrix.goos }}-${{ matrix.goarch }}.tgz wechatrobot README.md

      - name: Uploading assets
        if: ${{ !env.ACT }}
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./wechatrobot-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
          asset_name: wechatrobot-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
          asset_content_type: application/gzip